# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weat.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(589, 388)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        self.pushButton.clicked.connect(self.teller)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.SpanningRole, self.pushButton_2)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.label_7)

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(self.lineEdit_5.clear)
        self.pushButton_2.clicked.connect(self.lineEdit_6.clear)
        self.pushButton_2.clicked.connect(self.lineEdit_4.clear)
        self.pushButton_2.clicked.connect(self.lineEdit_3.clear)
        self.pushButton_2.clicked.connect(self.lineEdit_2.clear)
        self.pushButton_2.clicked.connect(self.lineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Weathering With You"))
        self.label.setText(_translate("Form", "Enter city name"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Enter city name"))
        self.pushButton.setText(_translate("Form", "Find Weather"))
        self.label_2.setText(_translate("Form", "Temperature (in degree celcius)"))
        self.label_3.setText(_translate("Form", "Atmospheric pressure (in hPa unit)"))
        self.label_4.setText(_translate("Form", "Humidity (in percentage)"))
        self.label_5.setText(_translate("Form", "Description"))
        self.pushButton_2.setText(_translate("Form", "Clear All"))
        self.label_6.setText(_translate("Form", "Weather Finder"))
        self.label_7.setText(_translate("Form", "Other messages"))

    def teller(self):

        city = self.lineEdit.text()
        import driver
        x = driver.forcaster(city)

        if x["cod"] != "404":

            y = x["main"]

            current_temperature = y["temp"]

            current_pressure = y["pressure"]

            current_humidiy = y["humidity"]

            z = x["weather"]

            weather_description = z[0]["description"]

            self.lineEdit_2.setText(str(current_temperature-273.15))
            self.lineEdit_3.setText(str(current_pressure))
            self.lineEdit_4.setText(str(current_humidiy))
            self.lineEdit_5.setText(str(weather_description))



        else:
            self.lineEdit_6.setText('City Not Found')


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
